"""
Real Google ADK Multi-Agent Example (Production Ready)

This shows how to use Google ADK with actual generative AI models.
Requires: GOOGLE_API_KEY environment variable

3 Agents:
1. ResearcherAgent - Investigates topics
2. EvaluatorAgent - Evaluates findings
3. ReporterAgent - Creates reports
"""

import os
from typing import Optional
from dotenv import load_dotenv

load_dotenv()

# Uncomment when Google ADK is properly installed
# from google.generativeai import adk

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")


class ResearcherAgent:
    """
    Agent that researches a topic
    Simple: takes topic, returns research findings
    """

    def __init__(self, model: str = "gemini-2.0-flash"):
        self.name = "Researcher"
        self.role = "Investigates and gathers information"
        self.model = model

    def research(self, topic: str) -> str:
        """
        Research a given topic

        Args:
            topic: Topic to research

        Returns:
            Research findings as string
        """

        prompt = f"""
Research the following topic and provide key findings:
Topic: {topic}

Please provide:
1. Overview (what is this?)
2. Key facts (3-5 important points)
3. Current trends
4. Market potential
5. Challenges

Keep it concise but informative.
"""

        # In production, uncomment:
        # response = client.models.generate_content(
        #     model=self.model,
        #     contents=prompt
        # )
        # return response.text

        # Fallback for testing (no API call)
        return f"Research findings for '{topic}':\n[Research data would be generated by {self.model}]"

    def __repr__(self):
        return f"<{self.name}Agent model={self.model}>"


class EvaluatorAgent:
    """
    Agent that evaluates research findings
    Simple: takes findings, returns evaluation
    """

    def __init__(self, model: str = "gemini-2.0-flash"):
        self.name = "Evaluator"
        self.role = "Evaluates and validates findings"
        self.model = model

    def evaluate(self, research_findings: str, criteria: str = "impact") -> str:
        """
        Evaluate research findings

        Args:
            research_findings: Findings from researcher
            criteria: What to evaluate on (impact, feasibility, value, etc)

        Returns:
            Evaluation as string
        """

        prompt = f"""
Evaluate the following research findings based on: {criteria}

Findings:
{research_findings}

Provide:
1. Strengths
2. Weaknesses
3. Opportunities
4. Risk assessment
5. Overall viability score (1-10)

Be analytical and critical.
"""

        # In production, uncomment:
        # response = client.models.generate_content(
        #     model=self.model,
        #     contents=prompt
        # )
        # return response.text

        # Fallback for testing
        return f"Evaluation based on '{criteria}':\n[Evaluation would be generated by {self.model}]"

    def __repr__(self):
        return f"<{self.name}Agent model={self.model}>"


class ReporterAgent:
    """
    Agent that creates reports from evaluation
    Simple: takes evaluation, returns formatted report
    """

    def __init__(self, model: str = "gemini-1.5-flash"):
        self.name = "Reporter"
        self.role = "Creates comprehensive reports"
        self.model = model

    def create_report(self, topic: str, evaluation: str, format: str = "executive") -> str:
        """
        Create a report from evaluation

        Args:
            topic: Topic being reported on
            evaluation: Evaluation findings
            format: "executive" (short) or "detailed" (long)

        Returns:
            Formatted report as string
        """

        prompt = f"""
Create a {format} report for the following:

Topic: {topic}

Evaluation:
{evaluation}

Format as:
- Executive Summary
- Key Findings
- Recommendations
- Next Steps

Keep it professional and clear.
"""

        # In production, uncomment:
        # response = client.models.generate_content(
        #     model=self.model,
        #     contents=prompt
        # )
        # return response.text

        # Fallback for testing
        return f"{format.title()} Report on '{topic}':\n[Report would be generated by {self.model}]"

    def __repr__(self):
        return f"<{self.name}Agent model={self.model}>"


class AgentOrchestrator:
    """
    Simple orchestrator that runs agents in sequence
    No complex logic - just chain: Research → Evaluate → Report
    """

    def __init__(self):
        self.researcher = ResearcherAgent(model="gemini-2.0-flash")
        self.evaluator = EvaluatorAgent(model="gemini-2.0-flash")
        self.reporter = ReporterAgent(model="gemini-1.5-flash")

    def execute_research_pipeline(
        self,
        topic: str,
        evaluation_criteria: str = "impact",
        report_format: str = "executive"
    ) -> dict:
        """
        Execute the research pipeline

        Args:
            topic: Topic to research
            evaluation_criteria: Criteria for evaluation
            report_format: "executive" or "detailed"

        Returns:
            Dictionary with outputs from each agent
        """

        print(f"\n{'='*70}")
        print(f"RESEARCH PIPELINE: {topic}")
        print(f"{'='*70}")

        # Agent 1: Research
        print(f"\n[1/3] 🔍 Researcher Agent")
        print(f"      Task: Research '{topic}'")
        print(f"      Model: {self.researcher.model}")
        research = self.researcher.research(topic)
        print(f"      Status: ✅ Complete")

        # Agent 2: Evaluate
        print(f"\n[2/3] 📊 Evaluator Agent")
        print(f"      Task: Evaluate findings ({evaluation_criteria})")
        print(f"      Model: {self.evaluator.model}")
        evaluation = self.evaluator.evaluate(research, criteria=evaluation_criteria)
        print(f"      Status: ✅ Complete")

        # Agent 3: Report
        print(f"\n[3/3] 📝 Reporter Agent")
        print(f"      Task: Create {report_format} report")
        print(f"      Model: {self.reporter.model}")
        report = self.reporter.create_report(topic, evaluation, format=report_format)
        print(f"      Status: ✅ Complete")

        print(f"\n{'='*70}")
        print(f"PIPELINE COMPLETE ✅")
        print(f"{'='*70}\n")

        return {
            "topic": topic,
            "research": research,
            "evaluation": evaluation,
            "report": report,
            "agents_used": [self.researcher, self.evaluator, self.reporter]
        }

    def print_result(self, result: dict):
        """Pretty print the pipeline result"""
        print(f"\n{'='*70}")
        print(f"RESEARCH RESULTS: {result['topic']}")
        print(f"{'='*70}")

        print(f"\n📌 RESEARCH FINDINGS:")
        print(f"{'-'*70}")
        print(result["research"][:200] + "...")

        print(f"\n📌 EVALUATION:")
        print(f"{'-'*70}")
        print(result["evaluation"][:200] + "...")

        print(f"\n📌 REPORT:")
        print(f"{'-'*70}")
        print(result["report"][:200] + "...")

        print(f"\n📌 AGENTS USED:")
        print(f"{'-'*70}")
        for agent in result["agents_used"]:
            print(f"  • {agent}")


def main():
    """Run the ADK example"""

    print("\n" + "="*70)
    print("GOOGLE ADK MULTI-AGENT RESEARCH PIPELINE")
    print("="*70)

    # Check API key
    if not GOOGLE_API_KEY:
        print("\n⚠️  GOOGLE_API_KEY not set. Using test mode (no API calls).")
        print("   To enable real API calls:")
        print("   1. Get key from: https://aistudio.google.com/app/apikey")
        print("   2. Set: export GOOGLE_API_KEY=your_key")
    else:
        print("\n✅ GOOGLE_API_KEY configured. Ready for API calls.")

    # Create orchestrator
    orchestrator = AgentOrchestrator()

    # Run research pipeline
    result = orchestrator.execute_research_pipeline(
        topic="Artificial Intelligence in 2026",
        evaluation_criteria="market impact and adoption",
        report_format="executive"
    )

    # Print results
    orchestrator.print_result(result)

    # Test with another topic (uncomment to run)
    # print("\n" + "#"*70)
    # print("Running another research cycle...")
    # print("#"*70)
    # result2 = orchestrator.execute_research_pipeline(
    #     topic="Quantum Computing",
    #     evaluation_criteria="feasibility and timeline",
    #     report_format="detailed"
    # )
    # orchestrator.print_result(result2)


if __name__ == "__main__":
    main()
